Repository Ciolv/SE2-Civilian, pull requests merged in 2022-06, with the labels that each got.

#35 Tasks
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/libraries/lib.xml
  .idea/misc.xml
  .idea/modules.xml
  SE2-Civilian.iml
  exports/airport-sim.csv
  exports/config.json
  pom.xml
  src/main/java/Plugin/Civilian/Person/Characteristic.java
  src/main/java/Plugin/Civilian/Person/Person.java
  src/main/java/Plugin/Task/Task.java
Labels: enhancement, sprint-2

#34 Implement Messages handling
  .idea/libraries/opencsv.xml
  src/main/java/Plugin/Civilian/Person/Civilian.java
  src/main/java/Plugin/Civilian/Person/Person.java
  src/main/java/Plugin/Task/CompletionTaskMessage.java
  src/main/java/Plugin/Task/Task.java
  src/main/java/Plugin/Task/TaskMessage.java
  src/main/java/Plugin/Task/TaskTimer.java
  src/main/java/Plugin/Task/TaskType.java
Labels: enhancement, sprint-3

#36 Feature
  .idea/compiler.xml
  src/main/java/Plugin/Civilian/Person/Civilian.java
  src/main/java/Plugin/Civilian/Person/Person.java
  src/main/java/Plugin/Task/Task.java
  src/main/java/Plugin/Task/TaskMessage.java
Labels: enhancement, sprint-3

#38 Refactoring
  .gitignore
  pom.xml
  src/main/java/Plugin/Civilian/Person/Civilian.java
  src/main/java/Plugin/Civilian/Person/CleaningWorker.java
  src/main/java/Plugin/Civilian/Person/Loader.java
  src/main/java/Plugin/Civilian/Person/LuggageDistributor.java
  src/main/java/Plugin/Civilian/Person/Person.java
  src/main/java/Plugin/Civilian/Person/TerminalWorker.java
  src/main/java/Plugin/Task/CompletionTaskMessage.java
  src/main/java/Plugin/Task/Task.java
  src/main/java/Plugin/Task/TaskMessage.java
Labels: enhancement

#40 Documentation
  src/main/java/Plugin/Civilian/Person/Characteristic.java
  src/main/java/Plugin/Civilian/Person/Civilian.java
  src/main/java/Plugin/Civilian/Person/CleaningWorker.java
  src/main/java/Plugin/Civilian/Person/Loader.java
  src/main/java/Plugin/Civilian/Person/LuggageDistributor.java
  src/main/java/Plugin/Civilian/Person/Person.java
  src/main/java/Plugin/CivilianPlugin.java
  src/main/java/Plugin/Task/CompletionTaskMessage.java
  src/main/java/Plugin/Task/Task.java
  src/main/java/Plugin/Task/TaskMessage.java
  src/main/java/Plugin/Task/TaskTimer.java
  src/main/java/Plugin/Task/TaskType.java
Labels: documentation

#43 Add boarding TaskType
  src/main/java/Plugin/Civilian/Person/Civilian.java
  src/main/java/Plugin/Civilian/Person/TerminalWorker.java
  src/main/java/Plugin/Task/TaskType.java
Labels: enhancement, sprint-3

#41 Add configuration information
  README.md
Labels: documentation

#42 Add efficiency calculation
  src/main/java/Plugin/Civilian/Person/Person.java
  src/main/java/Plugin/CivilianPlugin.java
Labels: enhancement, sprint-3
